export default {
  Palette: {
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
  },
  Colors: {
    height: '90%',
  },
  goBack: {
    width: '20%',
    height: '50%',
    margin: '0 auto',
    display: 'inline-block',
    position: 'relative',
    cursor: 'pointer',
    marginBottom: '-4px',
    opacity: '1',
    backgroundColor: '#000',
  },

  copyButton: {
    color: 'white',
    background: 'rgba(255, 255, 255, 0.3)',
    width: '100px',
    height: '30px',
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginTop: '-15px',
    marginLeft: '-50px',
    display: 'inline-block',
    textAlign: 'center',
    outline: 'none',
    lineHeight: '30px',
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    border: 'none',
    fontSize: '1rem',
    textTransform: 'uppercase',
    textDecoration: 'none',
  },
};
